# Generated by Django 3.1.5 on 2021-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('time_happened', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
