# Generated by Django 3.1.6 on 2021-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sentiment', '0003_comment_actual_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
