# Generated by Django 3.1.6 on 2021-02-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sentiment', '0004_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stock_sentiment.ticker'),
        ),
    ]
