# Generated by Django 3.1.6 on 2021-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sentiment', '0005_comment_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='ticker_logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
