# Generated by Django 3.1.6 on 2021-04-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_sentiment', '0006_ticker_ticker_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
